# Generated by Django 4.0.6 on 2022-07-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polls',
            options={'verbose_name_plural': 'Polls'},
        ),
        migrations.RemoveField(
            model_name='polls',
            name='choice4',
        ),
        migrations.AddField(
            model_name='polls',
            name='choice1_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polls',
            name='choice2_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polls',
            name='choice3_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='polls',
            name='choice3',
            field=models.CharField(max_length=200),
        ),
    ]
